### ISSUE TITLE
Photo galery

### ISSUE THREAD

**Issue by JanStihel** [cmauri/eva_facial_mouse#20]
It is not possible to open photos in the galery.

**Comment by cmauri** [comment]
As stated in the wizard: "Due to preexisting Android restrictions, some features are not currently available, yet. ... gallery and web browsers work with limitations".

For Android versions below 7.0 is not possible to mimic by software all actions you can manually perform using a touchscreen. This means that some applications functions (e.g. opening photos in the gallery) are not available, and most likely won't be in future.

As of Android 7.0 it is possible to simulate most touch gestures by software. We hope to add support for Android 7.0+ as soon as possible.
